# Generated by Django 4.2.7 on 2024-04-02 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='round',
        ),
    ]
