# Generated by Django 4.2.7 on 2024-03-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_remove_match_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='static/default_pfp.jpg', upload_to='profile_pics'),
        ),
    ]
