# Generated by Django 4.2.7 on 2024-04-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_remove_match_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='arenas',
            field=models.ManyToManyField(to='competitions.arena'),
        ),
    ]
