# Generated by Django 4.2.7 on 2024-03-01 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_roundrobintournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleeliminationtournament',
            name='prev_tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='competitions.roundrobintournament'),
        ),
    ]
