# Generated by Django 4.2.6 on 2024-03-05 03:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_singleeliminationtournament_prev_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('capacity', models.PositiveSmallIntegerField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='roundrobintournament',
            old_name='num_matches',
            new_name='num_rounds',
        ),
        migrations.AddField(
            model_name='abstracttournament',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 4, 21, 14, 34, 460325)),
        ),
        migrations.AddField(
            model_name='event',
            name='match_time',
            field=models.DurationField(default=datetime.datetime(2024, 3, 4, 21, 14, 53, 467631)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roundrobintournament',
            name='teams_per_match',
            field=models.PositiveSmallIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='arenas',
            field=models.ManyToManyField(blank=True, to='competitions.arena'),
        ),
        migrations.AddField(
            model_name='match',
            name='arena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match_set', to='competitions.arena'),
        ),
    ]
