# Generated by Django 4.2.7 on 2024-04-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_profile_bio_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roundrobintournament',
            options={'verbose_name': 'PreliminaryTournament'},
        ),
        migrations.RemoveField(
            model_name='abstracttournament',
            name='points',
        ),
        migrations.AddField(
            model_name='abstracttournament',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='singleeliminationtournament',
            name='points',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
