# Generated by Django 4.2.7 on 2024-06-01 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_competition_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='host',
        ),
    ]
