# Generated by Django 4.2.7 on 2024-03-05 19:09

from datetime import timedelta
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_singleeliminationtournament_prev_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('capacity', models.PositiveSmallIntegerField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='abstracttournament',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='match_time',
            field=models.DurationField(default=timedelta),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roundrobintournament',
            name='num_rounds',
            field=models.PositiveSmallIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roundrobintournament',
            name='teams_per_match',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='competition',
            name='arenas',
            field=models.ManyToManyField(blank=True, to='competitions.arena'),
        ),
        migrations.AddField(
            model_name='match',
            name='arena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match_set', to='competitions.arena'),
        ),
    ]
