# Generated by Django 4.2.7 on 2024-04-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_alter_roundrobintournament_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleeliminationtournament',
            name='points',
        ),
        migrations.AddField(
            model_name='abstracttournament',
            name='points',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
