# Generated by Django 4.2.7 on 2024-02-06 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_alter_team_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleeliminationtournament',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='prev_matches',
            field=models.ManyToManyField(blank=True, null=True, to='competitions.match'),
        ),
    ]
