# Generated by Django 4.2.7 on 2024-03-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_arena_abstracttournament_start_time_event_match_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='match_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
