# Generated by Django 4.2.7 on 2024-02-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_singleeliminationtournament_winner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='prev_matches',
            field=models.ManyToManyField(blank=True, to='competitions.match'),
        ),
    ]
