# Generated by Django 4.2.7 on 2024-04-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_remove_singleeliminationtournament_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='arenas',
            field=models.ManyToManyField(to='competitions.arena'),
        ),
    ]
