# Generated by Django 4.2.7 on 2024-03-05 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_alter_event_match_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roundrobintournament',
            name='num_matches',
        ),
    ]
