# Generated by Django 4.2.6 on 2024-03-05 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_remove_roundrobintournament_num_matches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='match_time',
            field=models.DurationField(default=datetime.timedelta(seconds=600)),
            preserve_default=False,
        ),
    ]
