# Generated by Django 4.2.7 on 2024-04-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_alter_competition_arenas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roundrobintournament',
            name='teams_per_match',
        ),
        migrations.AddField(
            model_name='abstracttournament',
            name='teams_per_match',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
