# Generated by Django 4.2.7 on 2024-02-06 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_alter_match_prev_matches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleeliminationtournament',
            name='winner',
        ),
    ]
