# Generated by Django 4.2.7 on 2024-06-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_remove_abstracttournament_max_teams_to_advance'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstracttournament',
            name='max_teams_to_advance',
            field=models.SmallIntegerField(default=1),
        ),
    ]
