# Generated by Django 4.2.6 on 2024-03-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_alter_event_match_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundrobintournament',
            name='points_per_loss',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roundrobintournament',
            name='points_per_tie',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roundrobintournament',
            name='points_per_win',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
