# Generated by Django 4.2.7 on 2024-02-07 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_remove_singleeliminationtournament_winner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ranking',
            unique_together={('tournament', 'rank')},
        ),
    ]
