# Generated by Django 4.2.6 on 2024-03-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_roundrobintournament_points_per_loss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
