# Generated by Django 4.2.7 on 2024-06-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_abstracttournament_max_teams_to_advance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstracttournament',
            name='max_teams_to_advance',
        ),
        migrations.AddField(
            model_name='abstracttournament',
            name='max_teams_per_match',
            field=models.SmallIntegerField(default=2),
        ),
    ]
