# Generated by Django 4.2.7 on 2024-04-11 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_alter_roundrobintournament_points_per_loss_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roundrobintournament',
            old_name='num_rounds',
            new_name='matches_per_team',
        ),
    ]
