# Generated by Django 4.2.7 on 2024-04-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_rename_num_rounds_roundrobintournament_matches_per_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='use_higher_score',
            field=models.BooleanField(default=True),
        ),
    ]
