# Generated by Django 4.2.7 on 2024-04-26 19:11

import competitions.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_rename_num_rounds_roundrobintournament_matches_per_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='round_num',
        ),
        migrations.AddField(
            model_name='abstracttournament',
            name='color',
            field=competitions.models.ColorField(default='#CBCBCB', image_field=None, max_length=25, samples=None),
        ),
    ]
