# Generated by Django 4.2.6 on 2024-03-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_match_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='round',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
