# Generated by Django 4.2.7 on 2024-06-01 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_remove_abstracttournament_max_teams_to_advance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstracttournament',
            name='max_teams_to_advance',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='competition',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.organization'),
        ),
    ]
