# Generated by Django 4.2.7 on 2024-03-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_alter_match_round'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='round',
            new_name='round_num',
        ),
        migrations.AlterField(
            model_name='roundrobintournament',
            name='points_per_tie',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='roundrobintournament',
            name='points_per_win',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
