# Generated by Django 4.2.7 on 2024-02-12 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_siteconfig'),
        ('competitions', '0010_alter_ranking_unique_together'),
    ]

    operations = [
    ]
