# Generated by Django 4.2.7 on 2024-04-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_event_use_higher_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='units',
            field=models.CharField(default='point', max_length=25),
        ),
        migrations.AddField(
            model_name='event',
            name='units_verbose',
            field=models.CharField(default='points', max_length=26),
        ),
        migrations.AddField(
            model_name='event',
            name='use_units',
            field=models.BooleanField(default=False),
        ),
    ]
