# Generated by Django 4.2.7 on 2024-04-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_remove_match_round_num_abstracttournament_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='round_num',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
