# Generated by Django 4.2.7 on 2024-04-29 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0011_match_round_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roundrobintournament',
            options={'verbose_name': 'Preliminary Tournament (Round Robin)', 'verbose_name_plural': 'Preliminary Tournaments (Round Robin)'},
        ),
    ]
