# Generated by Django 4.2.6 on 2024-05-09 19:14

import competitions.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0012_alter_roundrobintournament_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstracttournament',
            name='color',
        ),
        migrations.AddField(
            model_name='event',
            name='color',
            field=competitions.models.ColorField(default='#CBCBCB', image_field=None, max_length=25, samples=None),
        ),
    ]
