# Generated by Django 4.2.7 on 2024-04-30 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0011_event_units_event_units_verbose_event_use_units'),
        ('competitions', '0013_historicalmatch'),
    ]

    operations = [
    ]
