# Generated by Django 4.2.7 on 2024-05-06 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0014_merge_20240430_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsEarned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_earned_set', to='competitions.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_earned_set', to='competitions.team')),
            ],
        ),
    ]
