# Generated by Django 4.2.6 on 2024-05-22 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0014_biography'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Biography',
        ),
        migrations.AddField(
            model_name='abstracttournament',
            name='max_teams_to_advance',
            field=models.SmallIntegerField(default=1),
        ),
    ]
