# Generated by Django 4.2.7 on 2024-02-15 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0014_alter_competition_teams'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['sport', 'name']},
        ),
        migrations.AddField(
            model_name='event',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.sport'),
        ),
    ]
