# Generated by Django 4.2.7 on 2024-03-25 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0014_alter_arena_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundrobintournament',
            name='round',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
