# Generated by Django 4.2.7 on 2024-05-06 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0015_alter_arena_options_alter_event_options_and_more'),
        ('competitions', '0015_pointsearned'),
    ]

    operations = [
    ]
