# Generated by Django 4.2.7 on 2024-03-25 19:02

import competitions.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0015_merge_0012_match_round_0014_alter_arena_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arena',
            name='color',
            field=competitions.models.ColorField(default='#CBCBCB', max_length=7),
        ),
    ]
