# Generated by Django 4.2.8 on 2024-02-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0015_alter_event_options_event_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstracttournament',
            name='points',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
