# Generated by Django 4.2.7 on 2024-05-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0016_merge_20240506_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsearned',
            name='points',
            field=models.IntegerField(null=True),
        ),
    ]
