# Generated by Django 4.2.7 on 2024-03-25 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0015_roundrobintournament_round'),
        ('competitions', '0016_alter_arena_color'),
    ]

    operations = [
    ]
