# Generated by Django 4.2.8 on 2024-02-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0016_alter_abstracttournament_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
