# Generated by Django 4.2.7 on 2024-02-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0017_alter_match_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='_cached_str',
            field=models.TextField(blank=True, null=True),
        ),
    ]
