# Generated by Django 4.2.7 on 2024-05-20 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0017_alter_pointsearned_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.organization'),
        ),
    ]
