# Generated by Django 4.2.6 on 2024-02-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0018_alter_abstracttournament_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstracttournament',
            options={'ordering': ['competition', 'event']},
        ),
        migrations.AddField(
            model_name='match',
            name='_cached_str',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstracttournament',
            name='points',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
