# Generated by Django 4.2.7 on 2024-03-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0018_remove_roundrobintournament_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arena',
            name='color',
            field=models.CharField(default='#CBCBCB', max_length=7),
        ),
    ]
