# Generated by Django 4.2.7 on 2024-05-23 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0015_delete_biography_and_more'),
        ('competitions', '0019_alter_arena_capacity_alter_arena_owner_and_more'),
    ]

    operations = [
    ]
