# Generated by Django 4.2.6 on 2024-02-27 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0018_match__cached_str'),
        ('competitions', '0020_alter_match_tournament'),
    ]

    operations = [
    ]
